export { Friends } from "./dashboard/friends/friends"
export {Header} from "./dashboard/header/header"
export {Post} from "./dashboard/post/post"
export {User} from "./dashboard/user/user"
export {Signup} from "./Signup/Signup"
export {Login} from "./Login/login"